### ISSUE TITLE
Optional content.txt just for descriptions

### ISSUE THREAD

**Issue by ghost** [anno-mods/Modinfo#9]
It is noticeable that some descriptions are very long and do not fit so well into a json file. 

What do you think about the fact that you can optionally omit them but then provide a **content.txt**. 

Something similar to the previous one, but just for the description:

- content_en.txt
- content_de.txt

Using [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for language suffix

Hm.. what about **content.txt** (default as german or english?) ???

**Comment by jakobharder** [comment]
Possible with `file::README.md` now.
